// ============================================================================
//  NovaDroid - strings.cpp  UI localization: Russian (default) + English.
// ============================================================================
#include "app.h"

static const wchar_t* RU[] = {
    /* S_APP_NAME   */ L"NovaDroid Emulator",
    /* S_APP_SUB    */ L"Android x86_64 · v0.4.0 Universal (Stages 4-7)",
    /* S_NAV_HOME   */ L"Главная",
    /* S_NAV_INST   */ L"Мои инстансы",
    /* S_NAV_APK    */ L"Библиотека APK",
    /* S_NAV_FILES  */ L"Файлы",
    /* S_NAV_KEYS   */ L"Раскладка клавиш",
    /* S_NAV_PERF   */ L"Производительность",
    /* S_NAV_DIAG   */ L"Диагностика",
    /* S_NAV_LOGS   */ L"Логи",
    /* S_NAV_SET    */ L"Настройки",
    /* S_NAV_ABOUT  */ L"О программе",
    /* S_WELCOME    */ L"Добро пожаловать в NovaDroid",
    /* S_WELCOME_SUB*/ L"Запускайте Android x86_64 в виртуальной машине с аппаратным ускорением WHPX.",
    /* S_BTN_LAUNCH */ L"Запустить",
    /* S_BTN_STOP   */ L"Остановить",
    /* S_BTN_CREATE */ L"Создать инстанс",
    /* S_BTN_QUICK  */ L"Быстрый запуск",
    /* S_BTN_SAVE   */ L"Сохранить",
    /* S_BTN_CANCEL */ L"Отмена",
    /* S_BTN_ADD    */ L"Добавить APK",
    /* S_BTN_IMPORT */ L"Импорт",
    /* S_BTN_EXPORT */ L"Экспорт",
    /* S_BTN_BACKUP */ L"Резервная копия",
    /* S_BTN_RESTORE*/ L"Восстановить",
    /* S_BTN_DELETE */ L"Удалить",
    /* S_BTN_RENAME */ L"Переименовать",
    /* S_BTN_CLONE  */ L"Клонировать",
    /* S_BTN_CONFIG */ L"Настроить",
    /* S_BTN_OPENFOLDER*/ L"Открыть папку",
    /* S_BTN_RUN    */ L"Запустить",
    /* S_BTN_APPLY  */ L"Применить",
    /* S_ST_STOPPED */ L"Остановлен",
    /* S_ST_STARTING*/ L"Запускается",
    /* S_ST_RUNNING */ L"Работает",
    /* S_ST_PAUSED  */ L"Приостановлен",
    /* S_ST_STOPPING*/ L"Завершается",
    /* S_ST_ERROR   */ L"Ошибка запуска",
    /* S_ST_RECOVERY*/ L"Требуется восстановление",
    /* S_ST_UPDATING*/ L"Обновляется",
    /* S_SYS_STATE  */ L"Состояние системы",
    /* S_D_VIRT     */ L"Виртуализация CPU",
    /* S_D_WHPX     */ L"Windows Hypervisor Platform",
    /* S_D_QEMU     */ L"QEMU",
    /* S_D_ADB      */ L"ADB",
    /* S_D_IMAGE    */ L"Android-образ",
    /* S_D_RAM      */ L"Оперативная память",
    /* S_D_DISK     */ L"Место на диске",
    /* S_TB_TITLE   */ L"Управление (ADB)",
    /* S_TB_BACK    */ L"Назад",
    /* S_TB_HOME    */ L"Домой",
    /* S_TB_REC     */ L"Недавние",
    /* S_TB_VOLUP   */ L"Громкость +",
    /* S_TB_VOLDN   */ L"Громкость −",
    /* S_TB_SHOT    */ L"Скриншот",
    /* S_TB_ROT     */ L"Повернуть",
    /* S_TB_APK     */ L"Установить APK",
    /* S_TB_STOP    */ L"Выключить",
    /* S_TB_UPTIME  */ L"Время работы",
    /* S_TB_RAMDROP */ L"QEMU потребляет",
    /* S_LAST_APK   */ L"Последние APK",
    /* S_OPEN_APKLIB*/ L"Открыть библиотеку APK",
    /* S_INST_TITLE */ L"Мои инстансы",
    /* S_INST_SUB   */ L"Создавайте, запускайте и управляйте Android-инстансами.",
    /* S_BTN_FORCESTOP*/ L"Завершить принудительно",
    /* S_BTN_RESTART*/ L"Перезапустить",
    /* S_CTX_START  */ L"Запустить",
    /* S_CTX_STOP   */ L"Остановить",
    /* S_CTX_RESTART*/ L"Перезапустить",
    /* S_CTX_CONFIG */ L"Настроить…",
    /* S_CTX_RENAME */ L"Переименовать…",
    /* S_CTX_CLONE  */ L"Клонировать…",
    /* S_CTX_BACKUP */ L"Создать резервную копию",
    /* S_CTX_RESTORE*/ L"Восстановить из копии",
    /* S_CTX_EXPORT */ L"Экспортировать…",
    /* S_CTX_OPENF  */ L"Открыть папку инстанса",
    /* S_CTX_DELETE */ L"Удалить…",
    /* S_APK_TITLE  */ L"Библиотека APK",
    /* S_APK_SUB    */ L"Перетащите APK в окно или установите кнопкой на работающий инстанс.",
    /* S_APK_INSTALL*/ L"Установить",
    /* S_APK_OPEN   */ L"Открыть папку",
    /* S_APK_EMPTY  */ L"Библиотека пуста. Добавьте APK кнопкой или перетащите файл в окно.",
    /* S_APK_DND    */ L"Поддерживается Drag & Drop APK",
    /* S_APK_NORUN  */ L"Нет работающего инстанса — сначала запустите Android.",
    /* S_FILE_TITLE */ L"Файлы и общая папка",
    /* S_FILE_SUB   */ L"Обмен файлами между Windows и Android через ADB push/pull.",
    /* S_FILE_PICK  */ L"Передать файл в Android…",
    /* S_FILE_PUSH  */ L"Передать файл в Android",
    /* S_FILE_PULL  */ L"Забрать загрузки из Android",
    /* S_FILE_OPEN  */ L"Открыть общую папку",
    /* S_FILE_PATH  */ L"Общая папка (Windows)",
    /* S_FILE_EMPTY */ L"Операций ещё не было.",
    /* S_KEY_TITLE  */ L"Раскладка клавиш",
    /* S_KEY_SUB    */ L"Базовое управление доступно сразу, игровые профили — в версии 2.0.",
    /* S_KEY_NOTE   */ L"В MVP: клавиатура и мышь передаются в Android напрямую (мышь = касание).\nИгровая раскладка WASD, виртуальный джойстик и профили клавиш запланированы на v2.0.\nГорячие клавиши QEMU: Ctrl+Alt+F — полный экран, Ctrl+Alt+G — захват мыши, Ctrl+Alt+2 — монитор.",
    /* S_PERF_TITLE */ L"Производительность",
    /* S_PERF_SUB   */ L"Профили и параметры выбранного инстанса.",
    /* S_PERF_PROFILE*/ L"Профиль",
    /* S_PERF_ECO   */ L"Экономный",
    /* S_PERF_BAL   */ L"Сбалансированный",
    /* S_PERF_HIGH  */ L"Производительный",
    /* S_PERF_CUSTOM*/ L"Пользовательский",
    /* S_PERF_CPU   */ L"Ядра CPU",
    /* S_PERF_RAM   */ L"Память (MB)",
    /* S_PERF_DISKGB*/ L"Диск (GB)",
    /* S_PERF_RES   */ L"Разрешение",
    /* S_PERF_DPI   */ L"DPI",
    /* S_PERF_FPS   */ L"Лимит FPS",
    /* S_PERF_GPU   */ L"Режим GPU",
    /* S_PERF_PRIO  */ L"Приоритет процесса",
    /* S_PERF_APPLY */ L"Применить к инстансу",
    /* S_PERF_NOTE  */ L"Изменения CPU/RAM/диска применяются после перезапуска инстанса.",
    /* S_PRIO_N     */ L"Обычный",
    /* S_PRIO_H     */ L"Высокий",
    /* S_DIAG_TITLE */ L"Диагностика",
    /* S_DIAG_SUB   */ L"Проверка виртуализации, компонентов и ресурсов (ТЗ 6.10).",
    /* S_DIAG_RUN   */ L"Запустить проверку",
    /* S_DIAG_COPY  */ L"Скопировать отчёт",
    /* S_DIAG_OPENLOGS*/ L"Открыть папку логов",
    /* S_LOGS_TITLE */ L"Логи",
    /* S_LOGS_SUB   */ L"Журналы лаунчера, QEMU и ADB.",
    /* S_LOG_REFRESH*/ L"Обновить",
    /* S_LOG_FOLDER */ L"Открыть папку логов",
    /* S_LOG_CLEAN  */ L"Очистить старые (>14 дней)",
    /* S_LOG_COPY   */ L"Копировать в буфер",
    /* S_LOG_Launcher*/ L"Лаунчер",
    /* S_LOG_QEMU   */ L"QEMU",
    /* S_LOG_ADB    */ L"ADB",
    /* S_LOG_SERIAL */ L"Серийный вывод",
    /* S_LOG_EMPTY  */ L"Лог пуст.",
    /* S_SET_TITLE  */ L"Настройки",
    /* S_SET_SUB    */ L"Язык, пути к компонентам и поведение лаунчера.",
    /* S_SET_LANG   */ L"Язык интерфейса",
    /* S_SET_ACCENT */ L"Акцентный цвет",
    /* S_SET_QEMU   */ L"QEMU (qemu-system-x86_64.exe)",
    /* S_SET_ADB    */ L"ADB (adb.exe)",
    /* S_SET_IMAGE  */ L"Образ Android по умолчанию",
    /* S_SET_DATA   */ L"Папка данных",
    /* S_SET_CHECK  */ L"Проверять компоненты при запуске",
    /* S_SET_PORT   */ L"Базовый ADB-порт",
    /* S_SET_RESET  */ L"Сбросить",
    /* S_SET_PICK   */ L"Выбрать…",
    /* S_SET_RESTART*/ L"Изменение вступит в силу после перезапуска лаунчера.",
    /* S_SET_AUTORUN*/ L"Автозапуск последнего инстанса",
    /* S_AB_TITLE   */ L"О программе",
    /* S_AB_VER     */ L"NovaDroid Emulator 1.0.0 MVP",
    /* S_AB_ABOUT   */ L"Экспериментальный лаунчер Android x86_64 для Windows 11. Управляет виртуальными машинами QEMU с ускорением WHPX/Hyper-V и интеграцией ADB. Код лаунчера распространяется по лицензии MIT.",
    /* S_AB_COMP    */ L"Использованные открытые компоненты: QEMU (GPLv2+), Android-x86 (Apache/GPL), AOSP (Apache 2.0), Android SDK Platform Tools (Apache 2.0). Полные тексты — в файле THIRD_PARTY_LICENSES.txt.",
    /* S_AB_SAFE    */ L"Проект не содержит функций обхода античита, защиты приложений, банковских ограничений или детектирования эмулятора. ADB доступен только с localhost. Не собирайте и не отправляйте личные данные без вашего согласия.",
    /* S_AB_LINKS   */ L"Ссылки",
    /* S_DLG_CREATE */ L"Создание инстанса",
    /* S_DLG_EDIT   */ L"Настройка инстанса",
    /* S_DLG_NAME   */ L"Название инстанса",
    /* S_DLG_IMAGE  */ L"Android-образ (ISO или диск)",
    /* S_DLG_BROWSE */ L"Обзор…",
    /* S_DLG_BOOT   */ L"Загрузка",
    /* S_DLG_BOOT_ISO*/ L"ISO (live/установка)",
    /* S_DLG_BOOT_DISK*/ L"Диск (установленная ОС)",
    /* S_DLG_CPU    */ L"Ядра CPU",
    /* S_DLG_RAM    */ L"Память (MB)",
    /* S_DLG_DISK   */ L"Диск (GB)",
    /* S_DLG_RES    */ L"Разрешение",
    /* S_DLG_DPI    */ L"DPI",
    /* S_DLG_FPS    */ L"Частота кадров",
    /* S_DLG_GPU    */ L"Режим GPU",
    /* S_DLG_GPU_AUTO*/ L"Авто",
    /* S_DLG_GPU_STD */ L"Совместимый (VGA)",
    /* S_DLG_GPU_VIRT*/ L"VirtIO GPU",
    /* S_DLG_NET    */ L"Сеть",
    /* S_DLG_ADB    */ L"Включить ADB (только localhost)",
    /* S_DLG_SHARED */ L"Общая папка Windows",
    /* S_DLG_SHORTCUT*/ L"Создать ярлык на рабочем столе",
    /* S_DLG_SOUND  */ L"Звук включён",
    /* S_DLG_FULL   */ L"Полноэкранный режим",
    /* S_MB_DEL     */ L"Удалить инстанс вместе с виртуальным диском? Это действие необратимо.\n\nПеред удалением можно сохранить резервную копию.",
    /* S_MB_DELT    */ L"Удаление инстанса",
    /* S_MB_BAK     */ L"Включить диск в резервную копию?\n\n«Да» — полная копия (может занимать много места и занять время).\n«Нет» — только конфигурация и логи (быстро).",
    /* S_MB_RUNERR  */ L"Не удалось запустить инстанс.\n\nНе удалось включить аппаратное ускорение? Проверьте:\n1. В BIOS/UEFI включите Intel VT-x или AMD SVM.\n2. В компонентах Windows включите Windows Hypervisor Platform.\n3. Перезагрузите компьютер.\n4. Запустите диагностику повторно.\n\nПодробности в логах.",
    /* S_MB_STOPQ   */ L"Остановить все работающие инстансы перед выходом?",
    /* S_MB_STOPT   */ L"Выход из NovaDroid",
    /* S_MB_IMGMISS */ L"Не выбран Android-образ.\nУкажите путь к ISO/диску в настройках инстанса.",
    /* S_MB_QEMUMISS*/ L"QEMU не найден. Скопируйте qemu-system-x86_64.exe в папку app\\qemu\\ или укажите путь в настройках.",
    /* S_MB_ADBMISS */ L"ADB не найден. Скопируйте adb.exe (Android SDK Platform Tools) в папку app\\adb\\.",
    /* S_MB_DISKBUSY*/ L"Операция уже выполняется, подождите завершения.",
    /* S_MB_INSTALLED*/ L"APK успешно установлен",
    /* S_MB_INSTFAIL*/ L"Ошибка установки APK",
    /* S_MB_COPIED  */ L"Скопировано в буфер обмена",
    /* S_MB_RESTORED*/ L"Резервная копия восстановлена",
    /* S_MB_BADAPK  */ L"Выбранный файл не является APK. Установка прервана. Никогда не устанавливайте APK из недоверенных источников.",
    /* S_YES        */ L"Да",
    /* S_NO         */ L"Нет",
    /* S_OK2        */ L"ОК",
    /* S_ERR2       */ L"Ошибка",
    // ---- stage 2
    /* S_NAV_IMG    */ L"Образы Android",
    /* S_NAV_BACKUPS*/ L"Резервные копии",
    /* S_NAV_SNAPS  */ L"Снимки",
    /* S_ST2_PREP   */ L"Подготовка",
    /* S_ST2_WAIT   */ L"Ожидание загрузки",
    /* S_ST2_CLONING*/ L"Создаётся клон",
    /* S_ST2_BAK    */ L"Создаётся копия",
    /* S_ST2_REST   */ L"Восстанавливается",
    /* S_ST2_CORRUPT*/ L"Повреждён",
    /* S_IMG_TITLE  */ L"Образы Android x86_64",
    /* S_IMG_SUB    */ L"Встроенный каталог образов: скачайте и используйте в один клик",
    /* S_IMG_DOWNLOAD*/ L"Скачать",
    /* S_IMG_SHA    */ L"Проверить SHA-256",
    /* S_IMG_USE    */ L"Использовать",
    /* S_IMG_DELETE */ L"Удалить",
    /* S_IMG_LOCAL  */ L"Локальные образы",
    /* S_IMG_CATALOG*/ L"Каталог образов",
    /* S_IMG_DOWNLOADED*/ L"Загружен",
    /* S_IMG_NOTDL  */ L"Не скачан",
    /* S_IMG_OK     */ L"Хеш совпадает",
    /* S_IMG_FAIL   */ L"Хеш НЕ совпадает",
    /* S_IMG_CANCEL */ L"Отменить загрузку",
    /* S_IMG_USEDDEF*/ L"Образ назначен по умолчанию",
    /* S_IMG_HINT   */ L"Образы из папки images рядом с программой подхватываются автоматически. Устанавливайте образы только из официальных источников Android-x86.",
    /* S_IMG_SHACHECK*/ L"Проверка SHA-256 может занять минуту для большого файла",
    /* S_IMG_OPENMIRRORS*/ L"Открыть зеркало",
    /* S_BK_TITLE   */ L"Резервные копии",
    /* S_BK_SUB     */ L"Полные копии инстансов с manifest.json и SHA-256",
    /* S_BK_CREATE  */ L"Создать копию",
    /* S_BK_IMPORT  */ L"Импорт из файла",
    /* S_BK_RESTORE2*/ L"Восстановить",
    /* S_BK_EXPORT  */ L"Экспорт",
    /* S_BK_OPEN    */ L"Открыть папку",
    /* S_BK_EMPTY   */ L"Пока нет резервных копий",
    /* S_BK_MANIFEST*/ L"manifest: OK",
    /* S_BK_NOMAN   */ L"manifest: нет",
    /* S_BK_WITHSNAP*/ L"Включить снимки",
    /* S_BK_ASK     */ L"Создать резервную копию выбранного инстанса? Включить снимки?",
    /* S_SNAP_TITLE */ L"Снимки состояния",
    /* S_SNAP_SUB   */ L"Точки отката инстанса на основе QCOW2-снапшотов QEMU",
    /* S_SNAP_CREATE*/ L"Создать снимок",
    /* S_SNAP_RESTORE*/ L"Восстановить",
    /* S_SNAP_DELETE*/ L"Удалить",
    /* S_SNAP_PROT  */ L"защищён",
    /* S_SNAP_SYSTEM*/ L"системный",
    /* S_SNAP_USER  */ L"пользовательский",
    /* S_SNAP_AUTO  */ L"автоматический",
    /* S_SNAP_EMPTY */ L"Снимков ещё нет. Создайте первый снимок чистого состояния.",
    /* S_SNAP_WARNREST*/ L"Несохранённые данные после даты снимка будут потеряны! Перед восстановлением будет создана аварийная копия. Продолжить?",
    /* S_SNAP_NAME  */ L"Название снимка",
    /* S_SNAP_DESC  */ L"Описание (необязательно)",
    /* S_SNAP_PROT2 */ L"Защищённый снимок (нельзя удалить без подтверждения)",
    /* S_KM_TITLE   */ L"Раскладки клавиш",
    /* S_KM_SUB     */ L"Назначайте клавиши ПК на касания в Android. Только ручной ввод - без макросов и автоогня.",
    /* S_KM_ADDPROFILE*/ L"Новая раскладка",
    /* S_KM_ADDBIND */ L"Добавить привязку",
    /* S_KM_DELETE  */ L"Удалить",
    /* S_KM_EXPORT  */ L"Экспорт JSON",
    /* S_KM_IMPORT  */ L"Импорт JSON",
    /* S_KM_TOGGLE  */ L"Вкл/Выкл",
    /* S_KM_ON      */ L"ВКЛ",
    /* S_KM_OFF     */ L"ВЫКЛ",
    /* S_KM_ENGINE  */ L"Движок раскладки",
    /* S_KM_HOTKEY  */ L"Горячая клавиша режима: F1",
    /* S_KM_BINDS   */ L"Привязки",
    /* S_KM_NOBINDS */ L"Нет привязок в этой раскладке",
    /* S_KM_PRESSKEY*/ L"Нажмите любую клавишу...",
    /* S_KM_COORD   */ L"Координаты касания",
    /* S_KM_ACTION  */ L"Действие",
    /* S_KM_TAP     */ L"Касание",
    /* S_KM_LONGTAP */ L"Долгое нажатие",
    /* S_KM_SWIPE   */ L"Свайп",
    /* S_KM_BACKB   */ L"Назад",
    /* S_KM_HOMEB   */ L"Домой",
    /* S_KM_RECB    */ L"Недавние",
    /* S_KM_VOLUP   */ L"Громкость +",
    /* S_KM_VOLDN   */ L"Громкость -",
    /* S_KM_ROT     */ L"Повернуть",
    /* S_KM_NOTICE  */ L"Клавиши работают, когда окно Android активно и раскладка включена (F1). Ввод передаётся в гостевую систему как обычные касания.",
    /* S_KM_NAME    */ L"Название профиля",
    /* S_KM_PICK    */ L"Выберите координату на скриншоте",
    /* S_KM_HINTCLICK*/ L"Кликните по изображению, чтобы задать точку",
    /* S_KM_X       */ L"X",
    /* S_KM_Y       */ L"Y",
    /* S_KM_X2      */ L"X2",
    /* S_KM_Y2      */ L"Y2",
    /* S_KM_SHOT    */ L"Сделать скриншот",
    /* S_PERF2_TITLE*/ L"Центр производительности",
    /* S_PERF2_SUB  */ L"Живая статистика: CPU, RAM, диск за последние 60 секунд",
    /* S_PERF2_CPU  */ L"Загрузка CPU (QEMU)",
    /* S_PERF2_RAM  */ L"RAM процесса",
    /* S_PERF2_DISK */ L"Занято на диске",
    /* S_PERF2_NOINST*/ L"Нет запущенных инстансов. Запустите Android, чтобы увидеть статистику.",
    /* S_PERF2_REC  */ L"Рекомендации",
    /* S_PERF2_ECO  */ L"Экономный режим (без графиков)",
    /* S_PERF2_UPTIME*/ L"Время работы",
    /* S_PERF2_GPU  */ L"Режим GPU",
    /* S_WIZ_TITLE  */ L"Мастер создания инстанса",
    /* S_WIZ_STEP   */ L"Шаг",
    /* S_WIZ_NEXT   */ L"Далее →",
    /* S_WIZ_PREV   */ L"← Назад",
    /* S_WIZ_FINISH */ L"Готово",
    /* S_WIZ_NAME   */ L"Название инстанса",
    /* S_WIZ_TEMPLATE*/ L"Шаблон",
    /* S_WIZ_T_CLEAN*/ L"Чистый Android",
    /* S_WIZ_T_BAL  */ L"Сбалансированный",
    /* S_WIZ_T_PERF */ L"Производительный",
    /* S_WIZ_T_ECO  */ L"Экономный",
    /* S_WIZ_T_TEST */ L"Тестирование APK",
    /* S_WIZ_T_PORT */ L"Портретный телефон",
    /* S_WIZ_T_TAB  */ L"Альбомный планшет",
    /* S_WIZ_T_CUSTOM*/ L"Пользовательский",
    /* S_WIZ_PERF   */ L"Производительность",
    /* S_WIZ_SCREEN */ L"Экран устройства",
    /* S_WIZ_INTEG  */ L"Интеграция",
    /* S_WIZ_REVIEW */ L"Проверка",
    /* S_WIZ_ADBLOCK*/ L"ADB только на localhost (127.0.0.1) - обязательная защита",
    /* S_WIZ_SHARED */ L"Общая папка с Windows",
    /* S_WIZ_SHORTCUT*/ L"Ярлык на рабочем столе",
    /* S_WIZ_OPEN   */ L"Открыть Android после создания",
    /* S_WIZ_SNAP   */ L"Создать начальный снимок Clean Install",
    /* S_WIZ_PATH   */ L"Путь хранения",
    /* S_WIZ_SPACE  */ L"Требуемое свободное место",
    /* S_WIZ_CREATE */ L"Создать инстанс",
    /* S_WIZ_ORIENT */ L"Ориентация",
    /* S_WIZ_LAND   */ L"Альбомная",
    /* S_WIZ_PORT   */ L"Портретная",
    /* S_CLONE_TITLE*/ L"Клонирование инстанса",
    /* S_CLONE_FULL */ L"Полный клон",
    /* S_CLONE_LINKED*/ L"Связанный клон",
    /* S_CLONE_FULLD*/ L"Независимая копия диска. Надёжно, занимает место. Рекомендуется.",
    /* S_CLONE_LINKEDD*/ L"Быстро и компактно, но требует сохранности родительского диска.",
    /* S_CLONE_KEYMAPS*/ L"Копировать раскладки клавиш",
    /* S_CLONE_SHAREDC*/ L"Копировать содержимое общей папки",
    /* S_APKMI_TITLE*/ L"Установка APK в инстансы",
    /* S_APKMI_SUB  */ L"Выберите целевые инстансы (ADB должен быть подключён)",
    /* S_APKMI_INSTALL*/ L"Установить",
    /* S_APKMI_SNAPFIRST*/ L"Создавать снимок перед установкой",
    /* S_APKMI_RESULT*/ L"Результат",
    /* S_APKMI_TIME */ L"Время",
    /* S_APKMI_ERR  */ L"Ошибка",
    /* S_APKMI_DONE */ L"Установка завершена",
    /* S_APK_ADDLIB */ L"Добавить в библиотеку",
    /* S_APK_WARN   */ L"APK получен из внешнего источника. Устанавливайте только файлы, которым вы доверяете.",
    /* S_APK_DELETE2*/ L"Удалить из библиотеки (файл останется)",
    /* S_UPD_CHECK  */ L"Проверить обновления",
    /* S_UPD_CHANNEL*/ L"Канал обновлений",
    /* S_UPD_STABLE */ L"Stable",
    /* S_UPD_BETA   */ L"Beta",
    /* S_UPD_DEV    */ L"Development",
    /* S_SET_MAXRUN */ L"Лимит одновременных инстансов",
    /* S_MB_PARENTLINK*/ L"У этого инстанса есть связанные клоны. Удаление родительского диска сломает их. Продолжить?",
    /* S_MB_IMPORTOK*/ L"Импорт успешно завершён",
    /* S_DIAG_EXPORT*/ L"Экспорт отчёта",
    /* S_AB_VER2    */ L"0.4.0 Universal",
    // ---- stage 3 (TZ 3.0)
    /* S3_GPU_FB_HOST    */ L"GPU-режим Host недоступен. Использован SwiftShader. Обновите драйвер GPU для аппаратного ускорения.",
    /* S3_GPU_FB_DRIVER  */ L"Обнаружен проблемный драйвер GPU. Использован SwiftShader. Рекомендуется обновить драйвер GPU.",
    /* S3_GPU_FB_NOVIRGL */ L"Сборка QEMU без virtio-gpu-gl. Использован программный рендер SwiftShader.",
    /* S3_GPU_FB_NOWHPX  */ L"WHPX недоступен. Включите «Windows Hypervisor Platform» и виртуализацию в BIOS. Использован программный рендер.",
    /* S3_PROFILE_RUNNING*/ L"Остановите инстанс перед сменой профиля производительности.",
    /* S3_PKG_ERROR      */ L"Ошибка загрузки пакета",
    /* S3_PKG_DOWNLOAD   */ L"Скачивание полного пакета…",
    /* S3_PKG_EXTRACT    */ L"Распаковка пакета…",
    /* S3_PKG_VERIFY     */ L"Проверка SHA-256…",
    /* S3_PKG_DONE       */ L"Пакет установлен и проверен",
    /* S3_PKG_BADSHA     */ L"Контрольная сумма SHA-256 не совпала:",
    /* S3_PKG_BADSIZE    */ L"Размер файла не совпадает с ожидаемым",
    /* S3_PKG_NET        */ L"Не удалось скачать пакет",
    /* S3_PKG_SMALL      */ L"Файл слишком мал для пакета NovaDroid",
    /* S3_REC_TITLE      */ L"Восстановление после сбоя",
    /* S3_REC_QUESTION   */ L"Выберите действие:",
    /* S3_REC_SNAP       */ L"Восстановить последний снапшот",
    /* S3_REC_LOGS       */ L"Открыть логи",
    /* S3_REC_REPORT     */ L"Сохранить отчёт об ошибке (ZIP)",
    /* S3_REC_SAVED      */ L"Отчёт сохранён",
    /* S3_WIZ_TITLE      */ L"Полный пакет NovaDroid",
    /* S3_WIZ_SUB        */ L"При первом запуске программа скачивает полный пакет (QEMU + ADB + образ Android x86_64). Запуск эмулятора станет доступен после загрузки и проверки.",
    /* S3_WIZ_TOTAL      */ L"Всего",
    /* S3_WIZ_READY      */ L"Готово! Пакет скачан, проверен (SHA-256) и распакован. Эмулятор готов к запуску.",
    /* S3_WIZ_DOWNLOAD   */ L"Скачать пакет",
    /* S3_WIZ_OFFZIP     */ L"ZIP офлайн",
    /* S3_WIZ_VERIFY     */ L"Проверить файлы",
    /* S3_WIZ_PICKZIP    */ L"Укажите скачанный ZIP пакета",
    /* S3_WIZ_HIDE       */ L"Скрыть",
    /* S3_PKG_TITLE      */ L"Полный пакет (QEMU + ADB + образ Android)",
    /* S3_PKG_OK         */ L"Установлен",
    /* S3_PKG_PARTIAL    */ L"ВНИМАНИЕ: файлы пакета отсутствуют!",
    /* S3_PKG_NO         */ L"Не установлен. Запуск эмулятора заблокирован до загрузки пакета.",
    /* S3_PKG_REDOWNLOAD */ L"Перекачать",
    /* S3_PKG_STARTED    */ L"Загрузка пакета запущена",
    /* S3_PKG_BUSY       */ L"Загрузка уже выполняется",
    /* S3_PKG_VOK        */ L"Проверка пройдена",
    /* S3_PKG_VFAIL      */ L"Проверка не пройдена",
    /* S3_PROF_TITLE     */ L"Игровые профили производительности",
    /* S3_PROF_HINT      */ L"Профиль применяется к выбранному инстансу. Перед применением остановите инстанс.",
    /* S3_PROF_APPLIED   */ L"Профиль применён:",
    /* S3_GPU_TITLE      */ L"Состояние GPU",
    /* S3_G_TITLE        */ L"Графика и игра",
    /* S3_G_GPUMODE      */ L"GPU-режим",
    /* S3_G_BACKEND      */ L"GPU Backend",
    /* S3_G_SCALE        */ L"Масштабирование",
    /* S3_G_PROFILE      */ L"Профиль производительности",
    /* S3_G_BORDERLESS   */ L"Без рамки",
    /* S3_G_TOPMOST      */ L"Поверх всех окон",
    /* S3_G_VSYNC        */ L"VSync",
    /* S3_G_OVERLAY      */ L"Счётчик FPS в окне",
    /* S3_G_QUICKSTART   */ L"Быстрый старт",
    /* S3_G_VOLUME       */ L"Громкость, %",
    /* S3_G_MUTEMIN      */ L"Без звука при сворачивании",
    /* S3_G_INVY         */ L"Инверсия Y",
    /* S3_G_HOTKEY       */ L"Клавиша захвата мыши",
    /* S3_G_PROBE        */ L"Проверить GPU",
    /* S3_G_RESOLVED     */ L"Режим",
    /* S3_GPU_AUTO       */ L"Auto (авто)",
    /* S3_GPU_HOST       */ L"Host (GPU хоста)",
    /* S3_GPU_SWIFT      */ L"SwiftShader (программный быстрый)",
    /* S3_GPU_SOFT       */ L"Software (программный)",
    /* S3_BK_AUTO        */ L"Auto",
    /* S3_FPS_OFF        */ L"Без ограничения",
    /* S3_SC_FIT         */ L"Aspect Fit (пропорции)",
    /* S3_SC_STRETCH     */ L"Stretch (растянуть)",
    /* S3_SC_FILL        */ L"Aspect Fill (заполнить)",
    /* S3_SC_NATIVE      */ L"Native (1:1)",
    /* S3_TB_FULL        */ L"Экран (F11)",
    /* S3_TB_CAP         */ L"Мышь (RCtrl)",
    /* S3_TB_MUTE        */ L"Звук вкл/выкл",
    // ---- stage 4-7 (TZ 4-7)
    /* S4_ABI_OK         */ L"APK содержит x86_64 библиотеки. Совместимо.",
    /* S4_ABI_X86        */ L"APK содержит x86 библиотеки. Совместимо (32-бит).",
    /* S4_ABI_ARM        */ L"APK содержит только ARM библиотеки. Возможны проблемы.",
    /* S4_ABI_UNIVERSAL  */ L"APK без нативных библиотек — универсальный. Совместимо.",
    /* S4_ABI_UNKNOWN    */ L"Не удалось определить ABI APK.",
    /* S4_ABI_NOLIBS     */ L"нет нативных библиотек",
    /* S4_NET_RESULT     */ L"Сеть",
    /* S4_NET_FIXFAIL    */ L"Не удалось применить DNS. Попробуйте перезапустить инстанс.",
    /* S4_NET_INETOK     */ L"Интернет OK",
    /* S4_NET_INETFAIL   */ L"Интернет FAIL",
    /* S4_NET_DIAG       */ L"Диагностика сети",
    /* S4_NET_FIXDNS     */ L"DNS 8.8.8.8 / 1.1.1.1",
    /* S4_NET_RESETDNS   */ L"Сбросить DNS",
    /* S4_NET_RUNNING    */ L"Идёт диагностика...",
    /* S4_NET_FIXED      */ L"DNS применён (8.8.8.8, 1.1.1.1). Сохранено в конфиг инстанса.",
    /* S4_NET_RESETOK    */ L"DNS сброшен на 10.0.2.3 (при следующем запуске).",
    /* S4_SENS_FAIL      */ L"Не удалось. Проверьте, что инстанс запущен и ADB подключён.",
    /* S4_SENS_OK        */ L"Применено.",
    /* S4_GPS_BADFMT     */ L"Формат: широта,долгота (например 55.7558,37.6173).",
    /* S4_PROF_OK        */ L"Профиль применён.",
    /* S4_APP_PUBG       */ L"Возможны проблемы античита на некоторых серверах",
    /* S4_APP_APPLIED    */ L"Профиль приложения применён: %s",
    /* S4_COM_TITLE      */ L"Совместимость",
    /* S4_COM_SUB        */ L"Анализ APK (ABI), профили устройств и приложений",
    /* S4_COM_APK        */ L"Анализ APK",
    /* S4_COM_APKHINT    */ L"Проверка архитектуры (ABI), версии и SDK-требований APK перед установкой.",
    /* S4_COM_ANALYZE    */ L"Выбрать APK...",
    /* S4_COM_RESCAN     */ L"Дозаполнить библиотеку",
    /* S4_COM_RESCANNED  */ L"Библиотека APK дополнена данными об ABI.",
    /* S4_COM_PKG        */ L"Пакет",
    /* S4_NOSEL          */ L"Сначала выберите инстанс",
    /* S4_COM_DEV        */ L"Профили устройств",
    /* S4_COM_DEVSUB     */ L"Применить к выбранному инстансу: %s",
    /* S4_COM_APP        */ L"Профили приложений",
    /* S4_COM_APPSUB     */ L"Рекомендуемые настройки применяются автоматически при установке APK.",
    /* S4_COM_APPLY      */ L"Применить",
    /* S4_COM_WARN       */ L"Гарантия работы всех игр и приложений не предоставляется. Античит-системы (подмена идентификации устройства) не обходятся и не будут обходиться.",
    /* S4_SENS_TITLE     */ L"Датчики и сеть",
    /* S4_SENS_SUB       */ L"GPS, ориентация, батарея, диагностика сети выбранного инстанса",
    /* S4_NET_TITLE      */ L"Сеть (10.0.2.x)",
    /* S4_NET_HINT       */ L"Стандартная модель: шлюз 10.0.2.1, хост 10.0.2.2, DNS 10.0.2.3. Ручной DNS сохраняется в конфиг.",
    /* S4_GPS_TITLE      */ L"GPS",
    /* S4_GPS_HINT       */ L"Установка координат (работает в приложениях с поддержкой mock-локаций).",
    /* S4_GPS_SET        */ L"Установить",
    /* S4_GPS_CUSTOM     */ L"Свои координаты: широта,долгота",
    /* S4_ORI_TITLE      */ L"Ориентация / акселерометр",
    /* S4_ORI_HINT       */ L"Поворот экрана инстанса (блокировка автоповорота).",
    /* S4_BAT_TITLE      */ L"Батарея",
    /* S4_BAT_HINT       */ L"Уровень заряда и состояние (зарядка/разрядка).",
    /* S4_BAT_SET        */ L"Установить",
    /* S4_BAT_RESET      */ L"Сброс",
    /* S4_BAT_CUSTOM     */ L"Свой уровень: 0-100 (состояние — зарядка)",
    /* S4_ADV_TITLE      */ L"Продвинутые",
    /* S4_ADV_SUB        */ L"Обновления, стрим, плагины, облако, макросы, синхро, Discord",
    /* S4_UPD_TITLE      */ L"Обновления",
    /* S4_UPD_CUR        */ L"Текущая версия",
    /* S4_UPD_CHANNEL    */ L"Канал",
    /* S4_UPD_AVAIL      */ L"Доступна версия %s — можно установить.",
    /* S4_UPD_LATEST     */ L"У вас последняя версия.",
    /* S4_UPD_INSTALL    */ L"Установить",
    /* S4_UPD_CHANGETO   */ L"Канал",
    /* S4_UPD_NOFEED     */ L"Источник обновлений не настроен (updates.json).",
    /* S4_UPD_DLFAIL     */ L"Ошибка скачивания",
    /* S4_UPD_BADSHA     */ L"Проверка SHA-256 не пройдена. Обновление отменено.",
    /* S4_UPD_SWAPFAIL   */ L"Не удалось заменить exe (запущен?).",
    /* S4_UPD_ROLLBACK   */ L"Ошибка установки, выполнен откат.",
    /* S4_LOG_TITLE      */ L"Логи и экспорт",
    /* S4_LOG_HINT       */ L"Сбор логов QEMU + лаунчера + Android logcat в ZIP.",
    /* S4_LOG_EXPORT     */ L"Экспортировать логи (ZIP)",
    /* S4_LOG_ZIPPING    */ L"Собираю логи...",
    /* S4_LOG_DONE       */ L"Готово: %s",
    /* S4_LOG_FAIL       */ L"Не удалось собрать логи.",
    /* S4_BASEPART       */ L"Часть приложений не установилась (см. лог).",
    /* S4_BASEDONE       */ L"Базовые приложения установлены (F-Droid, APKPure).",
    /* S4_STR_TITLE      */ L"Просмотр в браузере",
    /* S4_STR_HINT       */ L"Стрим экрана Android + управление мышью/клавиатурой. Доступ только с localhost, ссылка с токеном.",
    /* S4_STR_START      */ L"Начать трансляцию",
    /* S4_STR_STOP       */ L"Остановить трансляцию",
    /* S4_STR_OPEN       */ L"Открыть в браузере",
    /* S4_STR_LOCAL      */ L"только localhost",
    /* S4_STR_BUSY       */ L"Трансляция уже запущена.",
    /* S4_STR_PORTBUSY   */ L"Порт %d занят.",
    /* S4_PLG_TITLE      */ L"Плагины",
    /* S4_PLG_HINT       */ L"DLL + manifest.json в папке plugins. Проверка SHA-256 перед загрузкой.",
    /* S4_PLG_EMPTY      */ L"Плагинов нет. Положите их в %s рядом с программой.",
    /* S4_PLG_INVALID    */ L"Повреждён или не пройдена проверка хэша",
    /* S4_PLG_ON         */ L"Включить",
    /* S4_PLG_OFF        */ L"Выключить",
    /* S4_PLG_RESCAN     */ L"Пересканировать",
    /* S4_PLG_RESCANNED  */ L"Плагины пересканированы.",
    /* S4_CLD_TITLE      */ L"Облачные бэкапы",
    /* S4_CLD_PROV       */ L"Провайдер",
    /* S4_CLD_NOTSET     */ L"не настроен",
    /* S4_CLD_ENC        */ L"AES-256 шифрование",
    /* S4_CLD_NOENC      */ L"без шифрования",
    /* S4_CLD_SETUP      */ L"Настроить",
    /* S4_CLD_NOPROV     */ L"Провайдер не поддерживается.",
    /* S4_CLD_NOTSET2    */ L"Сначала настройте облако.",
    /* S4_CLD_NOFILES    */ L"Бэкапов в облаке не найдено.",
    /* S4_CLD_PICKFILE   */ L"Имя файла для восстановления:",
    /* S4_CLD_NOTHING    */ L"Нет данных для бэкапа.",
    /* S4_CLD_UPOK       */ L"Бэкап загружен в облако.",
    /* S4_CLD_UPFAIL     */ L"Ошибка бэкапа",
    /* S4_CLD_RESOK      */ L"Восстановление завершено. Перезапустите программу.",
    /* S4_CLD_RESFAIL    */ L"Ошибка восстановления",
    /* S4_CLD_SETUPT     */ L"Облако",
    /* S4_CLD_SERVER     */ L"Сервер",
    /* S4_CLD_TOKEN      */ L"Токен (OAuth / user:pass)",
    /* S4_CLD_ENC_ON     */ L"Шифрование AES-256: ВКЛ",
    /* S4_CLD_ENC_OFF    */ L"Шифрование AES-256: ВЫКЛ",
    /* S4_CLD_NOTE       */ L"Токен хранится локально и не включается в бэкап. В бэкап входят: настройки, раскладки, список APK, макросы.",
    /* S4_MAC_TITLE      */ L"Макросы и автоматизация",
    /* S4_MAC_WARN       */ L"Внимание: использование макросов в онлайн-играх может привести к блокировке аккаунта.",
    /* S4_MAC_EMPTY      */ L"Запишите первый макрос кнопкой ниже (Esc — стоп).",
    /* S4_MAC_STEPS      */ L"шагов",
    /* S4_MAC_EDIT       */ L"Изменить",
    /* S4_MAC_PLAY       */ L"Играть",
    /* S4_MAC_STOP       */ L"Стоп",
    /* S4_MAC_DEL        */ L"Удалить",
    /* S4_MAC_REC        */ L"Записать макрос",
    /* S4_MAC_STOPREC    */ L"Остановить запись",
    /* S4_MAC_RECON      */ L"Идёт запись (Esc — стоп). Кликайте по окну эмулятора.",
    /* S4_MAC_SAVED      */ L"Макрос записан: %d шагов.",
    /* S4_MAC_DEFNAME    */ L"Макрос %s",
    /* S4_MAC_NORUN      */ L"Инстанс не запущен.",
    /* S4_MAC_PLAYING    */ L"Макрос уже воспроизводится.",
    /* S4_MAC_PLAYDONE   */ L"Воспроизведение завершено.",
    /* S4_MAC_DELETED    */ L"Макрос удалён.",
    /* S4_MAC_EDITORT    */ L"Редактор макроса",
    /* S4_MAC_NOHOT      */ L"Горячая клавиша",
    /* S4_MAC_REPEAT     */ L"Повторы",
    /* S4_MAC_ADDTAP     */ L"+ Клик",
    /* S4_MAC_ADDKEY    */ L"+ Клавиша",
    /* S4_MAC_ADDWAIT    */ L"+ Ожидание",
    /* S4_MAC_ADDTEXT    */ L"+ Текст",
    /* S4_MAC_DELSTEP    */ L"- Шаг",
    /* S4_SYN_TITLE      */ L"Синхронизация окон",
    /* S4_SYN_HINT       */ L"Мастер-инстанс управляет ведомыми: клики, клавиши и макросы дублируются.",
    /* S4_SYN_NONE       */ L"Групп нет. Выберите работающий инстанс и добавьте группу.",
    /* S4_SYN_ADD        */ L"Создать группу (мастер = выбранный)",
    /* S4_SYN_REMOVE     */ L"Удалить группу выбранного",
    /* S4_SYN_ISMASTER   */ L"Этот инстанс уже мастер другой группы.",
    /* S4_SYN_NOSLAVES   */ L"Нет других запущенных инстансов для ведомых.",
    /* S4_SYN_ADDED      */ L"Группа создана: %d ведомых.",
    /* S4_SYN_REMOVED    */ L"Группа удалена.",
    /* S4_ALG_TITLE      */ L"Анти-лаг и FPS",
    /* S4_ALG_HINT       */ L"При просадках FPS: приоритет процесса повышен, рекомендации по качеству.",
    /* S4_ALG_ON         */ L"Анти-лаг: ВКЛ",
    /* S4_ALG_OFF        */ L"Анти-лаг: ВЫКЛ",
    /* S4_DSC_TITLE      */ L"Discord Rich Presence",
    /* S4_DSC_HINT       */ L"«Играет в <инстанс> через NovaDroid». Нужен запущенный Discord. Client ID свой — в настройках.",
    /* S4_DSC_ON         */ L"Включить",
    /* S4_DSC_OFF        */ L"Выключить",
    /* S4_PRO_HINT       */ L"Pro: приоритетная поддержка, ранний доступ, расширенные макросы, эксклюзивные темы.",
    /* S4_PRO_ACT        */ L"Активировать ключ",
    /* S4_PRO_ACTIVE     */ L"Pro активирован",
    /* S4_PRO_ISACTIVE   */ L"Ключ: %s",
    /* S4_PRO_ENTER      */ L"Ключ NovaDroid Pro",
    /* S4_PRO_OK         */ L"NovaDroid Pro активирован. Спасибо!",
    /* S4_PRO_BAD        */ L"Неверный формат ключа (NOVA-XXXX-...).",
    /* S4_NAV_COMPAT     */ L"Совместимость",
    /* S4_NAV_SENSORS    */ L"Датчики и сеть",
    /* S4_NAV_ADVANCED   */ L"Продвинутые",
    /* S4_WIZ_WELCOME    */ L"Добро пожаловать в NovaDroid",
    /* S4_WIZ_CHECK      */ L"Проверка системы",
    /* S4_WIZ_LANG       */ L"Язык интерфейса",
    /* S4_WIZ_THEME      */ L"Тема оформления",
    /* S4_WIZ_INST       */ L"Первый инстанс",
    /* S4_WIZ_DONE       */ L"Всё готово",
    /* S4_WIZ_STEP       */ L"Шаг",
    /* S4_WIZ_WELCOMETXT */ L"Мастер настроит NovaDroid за пять шагов: проверка системы, язык, тема и создание первого инстанса Android.",
    /* S4_WIZ_NOVIRT     */ L"Включите VT-x/AMD-V в BIOS",
    /* S4_WIZ_NOWHPX     */ L"Включите компонент Windows Hypervisor Platform",
    /* S4_WIZ_DISK       */ L"Диск",
    /* S4_WIZ_SYSWARN    */ L"Не все требования выполнены — возможны проблемы с производительностью.",
    /* S4_WIZ_DARK       */ L"Тёмная",
    /* S4_WIZ_LIGHT      */ L"Светлая",
    /* S4_WIZ_SYS        */ L"Как в системе",
    /* S4_WIZ_LAUNCH     */ L"Запустить NovaDroid",
    /* S4_WIZ_DOCS       */ L"Открыть документацию",
    /* S4_WIZ_DONETXT    */ L"Готово! Первый инстанс создан. Документация доступна в разделе «О программе» и в папке docs.",
};

static const wchar_t* EN[] = {
    /* S_APP_NAME   */ L"NovaDroid Emulator",
    /* S_APP_SUB    */ L"Android x86_64 · v0.4.0 Universal (Stages 4-7)",
    /* S_NAV_HOME   */ L"Home",
    /* S_NAV_INST   */ L"My instances",
    /* S_NAV_APK    */ L"APK library",
    /* S_NAV_FILES  */ L"Files",
    /* S_NAV_KEYS   */ L"Keymapping",
    /* S_NAV_PERF   */ L"Performance",
    /* S_NAV_DIAG   */ L"Diagnostics",
    /* S_NAV_LOGS   */ L"Logs",
    /* S_NAV_SET    */ L"Settings",
    /* S_NAV_ABOUT  */ L"About",
    /* S_WELCOME    */ L"Welcome to NovaDroid",
    /* S_WELCOME_SUB*/ L"Run Android x86_64 in a VM with WHPX hardware acceleration.",
    /* S_BTN_LAUNCH */ L"Launch",
    /* S_BTN_STOP   */ L"Stop",
    /* S_BTN_CREATE */ L"Create instance",
    /* S_BTN_QUICK  */ L"Quick launch",
    /* S_BTN_SAVE   */ L"Save",
    /* S_BTN_CANCEL */ L"Cancel",
    /* S_BTN_ADD    */ L"Add APK",
    /* S_BTN_IMPORT */ L"Import",
    /* S_BTN_EXPORT */ L"Export",
    /* S_BTN_BACKUP */ L"Backup",
    /* S_BTN_RESTORE*/ L"Restore",
    /* S_BTN_DELETE */ L"Delete",
    /* S_BTN_RENAME */ L"Rename",
    /* S_BTN_CLONE  */ L"Clone",
    /* S_BTN_CONFIG */ L"Configure",
    /* S_BTN_OPENFOLDER*/ L"Open folder",
    /* S_BTN_RUN    */ L"Launch",
    /* S_BTN_APPLY  */ L"Apply",
    /* S_ST_STOPPED */ L"Stopped",
    /* S_ST_STARTING*/ L"Starting",
    /* S_ST_RUNNING */ L"Running",
    /* S_ST_PAUSED  */ L"Paused",
    /* S_ST_STOPPING*/ L"Stopping",
    /* S_ST_ERROR   */ L"Start error",
    /* S_ST_RECOVERY*/ L"Needs recovery",
    /* S_ST_UPDATING*/ L"Updating",
    /* S_SYS_STATE  */ L"System state",
    /* S_D_VIRT     */ L"CPU virtualization",
    /* S_D_WHPX     */ L"Windows Hypervisor Platform",
    /* S_D_QEMU     */ L"QEMU",
    /* S_D_ADB      */ L"ADB",
    /* S_D_IMAGE    */ L"Android image",
    /* S_D_RAM      */ L"Memory",
    /* S_D_DISK     */ L"Disk space",
    /* S_TB_TITLE   */ L"Controls (ADB)",
    /* S_TB_BACK    */ L"Back",
    /* S_TB_HOME    */ L"Home",
    /* S_TB_REC     */ L"Recents",
    /* S_TB_VOLUP   */ L"Volume +",
    /* S_TB_VOLDN   */ L"Volume −",
    /* S_TB_SHOT    */ L"Screenshot",
    /* S_TB_ROT     */ L"Rotate",
    /* S_TB_APK     */ L"Install APK",
    /* S_TB_STOP    */ L"Power off",
    /* S_TB_UPTIME  */ L"Uptime",
    /* S_TB_RAMDROP */ L"QEMU usage",
    /* S_LAST_APK   */ L"Recent APKs",
    /* S_OPEN_APKLIB*/ L"Open APK library",
    /* S_INST_TITLE */ L"My instances",
    /* S_INST_SUB   */ L"Create, launch and manage Android instances.",
    /* S_BTN_FORCESTOP*/ L"Force stop",
    /* S_BTN_RESTART*/ L"Restart",
    /* S_CTX_START  */ L"Launch",
    /* S_CTX_STOP   */ L"Stop",
    /* S_CTX_RESTART*/ L"Restart",
    /* S_CTX_CONFIG */ L"Configure…",
    /* S_CTX_RENAME */ L"Rename…",
    /* S_CTX_CLONE  */ L"Clone…",
    /* S_CTX_BACKUP */ L"Create backup",
    /* S_CTX_RESTORE*/ L"Restore from backup",
    /* S_CTX_EXPORT */ L"Export…",
    /* S_CTX_OPENF  */ L"Open instance folder",
    /* S_CTX_DELETE */ L"Delete…",
    /* S_APK_TITLE  */ L"APK library",
    /* S_APK_SUB    */ L"Drag an APK into the window or install it to a running instance.",
    /* S_APK_INSTALL*/ L"Install",
    /* S_APK_OPEN   */ L"Open folder",
    /* S_APK_EMPTY  */ L"Library is empty. Add an APK or drag a file into the window.",
    /* S_APK_DND    */ L"Drag & Drop APK supported",
    /* S_APK_NORUN  */ L"No running instance — start Android first.",
    /* S_FILE_TITLE */ L"Files and shared folder",
    /* S_FILE_SUB   */ L"Exchange files between Windows and Android via ADB push/pull.",
    /* S_FILE_PICK  */ L"Send file to Android…",
    /* S_FILE_PUSH  */ L"Send file to Android",
    /* S_FILE_PULL  */ L"Fetch downloads from Android",
    /* S_FILE_OPEN  */ L"Open shared folder",
    /* S_FILE_PATH  */ L"Shared folder (Windows)",
    /* S_FILE_EMPTY */ L"No operations yet.",
    /* S_KEY_TITLE  */ L"Keymapping",
    /* S_KEY_SUB    */ L"Basic controls work out of the box; game profiles arrive in v2.0.",
    /* S_KEY_NOTE   */ L"MVP: keyboard and mouse are passed to Android directly (mouse = touch).\nWASD layout, virtual joystick and key profiles are planned for v2.0.\nQEMU hotkeys: Ctrl+Alt+F — fullscreen, Ctrl+Alt+G — grab mouse, Ctrl+Alt+2 — monitor.",
    /* S_PERF_TITLE */ L"Performance",
    /* S_PERF_SUB   */ L"Profiles and parameters of the selected instance.",
    /* S_PERF_PROFILE*/ L"Profile",
    /* S_PERF_ECO   */ L"Economy",
    /* S_PERF_BAL   */ L"Balanced",
    /* S_PERF_HIGH  */ L"Performance",
    /* S_PERF_CUSTOM*/ L"Custom",
    /* S_PERF_CPU   */ L"CPU cores",
    /* S_PERF_RAM   */ L"Memory (MB)",
    /* S_PERF_DISKGB*/ L"Disk (GB)",
    /* S_PERF_RES   */ L"Resolution",
    /* S_PERF_DPI   */ L"DPI",
    /* S_PERF_FPS   */ L"FPS limit",
    /* S_PERF_GPU   */ L"GPU mode",
    /* S_PERF_PRIO  */ L"Process priority",
    /* S_PERF_APPLY */ L"Apply to instance",
    /* S_PERF_NOTE  */ L"CPU/RAM/disk changes take effect after instance restart.",
    /* S_PRIO_N     */ L"Normal",
    /* S_PRIO_H     */ L"High",
    /* S_DIAG_TITLE */ L"Diagnostics",
    /* S_DIAG_SUB   */ L"Checks virtualization, components and resources (spec 6.10).",
    /* S_DIAG_RUN   */ L"Run check",
    /* S_DIAG_COPY  */ L"Copy report",
    /* S_DIAG_OPENLOGS*/ L"Open logs folder",
    /* S_LOGS_TITLE */ L"Logs",
    /* S_LOGS_SUB   */ L"Launcher, QEMU and ADB journals.",
    /* S_LOG_REFRESH*/ L"Refresh",
    /* S_LOG_FOLDER */ L"Open logs folder",
    /* S_LOG_CLEAN  */ L"Clean old (>14 days)",
    /* S_LOG_COPY   */ L"Copy to clipboard",
    /* S_LOG_Launcher*/ L"Launcher",
    /* S_LOG_QEMU   */ L"QEMU",
    /* S_LOG_ADB    */ L"ADB",
    /* S_LOG_SERIAL */ L"Serial output",
    /* S_LOG_EMPTY  */ L"Log is empty.",
    /* S_SET_TITLE  */ L"Settings",
    /* S_SET_SUB    */ L"Language, component paths and launcher behavior.",
    /* S_SET_LANG   */ L"Interface language",
    /* S_SET_ACCENT */ L"Accent color",
    /* S_SET_QEMU   */ L"QEMU (qemu-system-x86_64.exe)",
    /* S_SET_ADB    */ L"ADB (adb.exe)",
    /* S_SET_IMAGE  */ L"Default Android image",
    /* S_SET_DATA   */ L"Data folder",
    /* S_SET_CHECK  */ L"Check components on start",
    /* S_SET_PORT   */ L"Base ADB port",
    /* S_SET_RESET  */ L"Reset",
    /* S_SET_PICK   */ L"Browse…",
    /* S_SET_RESTART*/ L"Takes effect after launcher restart.",
    /* S_SET_AUTORUN*/ L"Autostart last instance",
    /* S_AB_TITLE   */ L"About",
    /* S_AB_VER     */ L"NovaDroid Emulator 1.0.0 MVP",
    /* S_AB_ABOUT   */ L"Experimental Android x86_64 launcher for Windows 11. Drives QEMU virtual machines with WHPX/Hyper-V acceleration and ADB integration. Launcher code is MIT licensed.",
    /* S_AB_COMP    */ L"Open components used: QEMU (GPLv2+), Android-x86 (Apache/GPL), AOSP (Apache 2.0), Android SDK Platform Tools (Apache 2.0). Full texts in THIRD_PARTY_LICENSES.txt.",
    /* S_AB_SAFE    */ L"This project contains no anti-cheat bypass, app protection bypass, banking restrictions bypass or emulator detection masking. ADB is localhost-only. No personal data is collected or sent without your consent.",
    /* S_AB_LINKS   */ L"Links",
    /* S_DLG_CREATE */ L"Create instance",
    /* S_DLG_EDIT   */ L"Configure instance",
    /* S_DLG_NAME   */ L"Instance name",
    /* S_DLG_IMAGE  */ L"Android image (ISO or disk)",
    /* S_DLG_BROWSE */ L"Browse…",
    /* S_DLG_BOOT   */ L"Boot from",
    /* S_DLG_BOOT_ISO*/ L"ISO (live/install)",
    /* S_DLG_BOOT_DISK*/ L"Disk (installed OS)",
    /* S_DLG_CPU    */ L"CPU cores",
    /* S_DLG_RAM    */ L"Memory (MB)",
    /* S_DLG_DISK   */ L"Disk (GB)",
    /* S_DLG_RES    */ L"Resolution",
    /* S_DLG_DPI    */ L"DPI",
    /* S_DLG_FPS    */ L"Frame rate",
    /* S_DLG_GPU    */ L"GPU mode",
    /* S_DLG_GPU_AUTO*/ L"Auto",
    /* S_DLG_GPU_STD */ L"Compatible (VGA)",
    /* S_DLG_GPU_VIRT*/ L"VirtIO GPU",
    /* S_DLG_NET    */ L"Network",
    /* S_DLG_ADB    */ L"Enable ADB (localhost only)",
    /* S_DLG_SHARED */ L"Windows shared folder",
    /* S_DLG_SHORTCUT*/ L"Create desktop shortcut",
    /* S_DLG_SOUND  */ L"Sound enabled",
    /* S_DLG_FULL   */ L"Fullscreen",
    /* S_MB_DEL     */ L"Delete the instance together with its virtual disk? This cannot be undone.\n\nYou may create a backup first.",
    /* S_MB_DELT    */ L"Delete instance",
    /* S_MB_BAK     */ L"Include the disk in the backup?\n\n'Yes' — full copy (large and slow).\n'No' — config and logs only (fast).",
    /* S_MB_RUNERR  */ L"Failed to start the instance.\n\nHardware acceleration not available? Check:\n1. Enable Intel VT-x or AMD SVM in BIOS/UEFI.\n2. Enable the Windows Hypervisor Platform feature.\n3. Reboot the computer.\n4. Run diagnostics again.\n\nSee logs for details.",
    /* S_MB_STOPQ   */ L"Stop all running instances before exit?",
    /* S_MB_STOPT   */ L"Exit NovaDroid",
    /* S_MB_IMGMISS */ L"No Android image selected.\nSet the ISO/disk path in instance settings.",
    /* S_MB_QEMUMISS*/ L"QEMU not found. Copy qemu-system-x86_64.exe into app\\qemu\\ or set the path in settings.",
    /* S_MB_ADBMISS */ L"ADB not found. Copy adb.exe (Android SDK Platform Tools) into app\\adb\\.",
    /* S_MB_DISKBUSY*/ L"An operation is already running, please wait.",
    /* S_MB_INSTALLED*/ L"APK installed successfully",
    /* S_MB_INSTFAIL*/ L"APK installation failed",
    /* S_MB_COPIED  */ L"Copied to clipboard",
    /* S_MB_RESTORED*/ L"Backup restored",
    /* S_MB_BADAPK  */ L"The selected file is not an APK. Installation aborted. Never install APKs from untrusted sources.",
    /* S_YES        */ L"Yes",
    /* S_NO         */ L"No",
    /* S_OK2        */ L"OK",
    /* S_ERR2       */ L"Error",
    // ---- stage 2
    /* S_NAV_IMG    */ L"Android Images",
    /* S_NAV_BACKUPS*/ L"Backups",
    /* S_NAV_SNAPS  */ L"Snapshots",
    /* S_ST2_PREP   */ L"Preparing",
    /* S_ST2_WAIT   */ L"Waiting for boot",
    /* S_ST2_CLONING*/ L"Cloning",
    /* S_ST2_BAK    */ L"Backing up",
    /* S_ST2_REST   */ L"Restoring",
    /* S_ST2_CORRUPT*/ L"Corrupted",
    /* S_IMG_TITLE  */ L"Android x86_64 Images",
    /* S_IMG_SUB    */ L"Built-in image catalog: download and use in one click",
    /* S_IMG_DOWNLOAD*/ L"Download",
    /* S_IMG_SHA    */ L"Verify SHA-256",
    /* S_IMG_USE    */ L"Use",
    /* S_IMG_DELETE */ L"Delete",
    /* S_IMG_LOCAL  */ L"Local images",
    /* S_IMG_CATALOG*/ L"Image catalog",
    /* S_IMG_DOWNLOADED*/ L"Downloaded",
    /* S_IMG_NOTDL  */ L"Not downloaded",
    /* S_IMG_OK     */ L"Hash matches",
    /* S_IMG_FAIL   */ L"Hash MISMATCH",
    /* S_IMG_CANCEL */ L"Cancel download",
    /* S_IMG_USEDDEF*/ L"Image set as default",
    /* S_IMG_HINT   */ L"Images from the images folder next to the app are detected automatically. Only install images from official Android-x86 sources.",
    /* S_IMG_SHACHECK*/ L"SHA-256 check may take a minute for large files",
    /* S_IMG_OPENMIRRORS*/ L"Open mirror",
    /* S_BK_TITLE   */ L"Backups",
    /* S_BK_SUB     */ L"Full instance copies with manifest.json and SHA-256",
    /* S_BK_CREATE  */ L"Create backup",
    /* S_BK_IMPORT  */ L"Import from file",
    /* S_BK_RESTORE2*/ L"Restore",
    /* S_BK_EXPORT  */ L"Export",
    /* S_BK_OPEN    */ L"Open folder",
    /* S_BK_EMPTY   */ L"No backups yet",
    /* S_BK_MANIFEST*/ L"manifest: OK",
    /* S_BK_NOMAN   */ L"manifest: missing",
    /* S_BK_WITHSNAP*/ L"Include snapshots",
    /* S_BK_ASK     */ L"Create a backup of the selected instance? Include snapshots?",
    /* S_SNAP_TITLE */ L"State snapshots",
    /* S_SNAP_SUB   */ L"Instance rollback points based on QEMU QCOW2 snapshots",
    /* S_SNAP_CREATE*/ L"Create snapshot",
    /* S_SNAP_RESTORE*/ L"Restore",
    /* S_SNAP_DELETE*/ L"Delete",
    /* S_SNAP_PROT  */ L"protected",
    /* S_SNAP_SYSTEM*/ L"system",
    /* S_SNAP_USER  */ L"user",
    /* S_SNAP_AUTO  */ L"auto",
    /* S_SNAP_EMPTY */ L"No snapshots yet. Create your first clean-state snapshot.",
    /* S_SNAP_WARNREST*/ L"Unsaved data made after the snapshot date will be lost! An emergency backup will be created first. Continue?",
    /* S_SNAP_NAME  */ L"Snapshot name",
    /* S_SNAP_DESC  */ L"Description (optional)",
    /* S_SNAP_PROT2 */ L"Protected snapshot (deletion requires confirmation)",
    /* S_KM_TITLE   */ L"Keymaps",
    /* S_KM_SUB     */ L"Map PC keys to Android touches. Manual input only - no macros, no auto-fire.",
    /* S_KM_ADDPROFILE*/ L"New layout",
    /* S_KM_ADDBIND */ L"Add binding",
    /* S_KM_DELETE  */ L"Delete",
    /* S_KM_EXPORT  */ L"Export JSON",
    /* S_KM_IMPORT  */ L"Import JSON",
    /* S_KM_TOGGLE  */ L"Toggle",
    /* S_KM_ON      */ L"ON",
    /* S_KM_OFF     */ L"OFF",
    /* S_KM_ENGINE  */ L"Keymap engine",
    /* S_KM_HOTKEY  */ L"Mode hotkey: F1",
    /* S_KM_BINDS   */ L"Bindings",
    /* S_KM_NOBINDS */ L"No bindings in this layout",
    /* S_KM_PRESSKEY*/ L"Press any key...",
    /* S_KM_COORD   */ L"Touch coordinates",
    /* S_KM_ACTION  */ L"Action",
    /* S_KM_TAP     */ L"Tap",
    /* S_KM_LONGTAP */ L"Long press",
    /* S_KM_SWIPE   */ L"Swipe",
    /* S_KM_BACKB   */ L"Back",
    /* S_KM_HOMEB   */ L"Home",
    /* S_KM_RECB    */ L"Recents",
    /* S_KM_VOLUP   */ L"Volume +",
    /* S_KM_VOLDN   */ L"Volume -",
    /* S_KM_ROT     */ L"Rotate",
    /* S_KM_NOTICE  */ L"Keys work while the Android window is active and the layout is ON (F1). Input is forwarded to the guest as ordinary touches.",
    /* S_KM_NAME    */ L"Profile name",
    /* S_KM_PICK    */ L"Pick a coordinate on the screenshot",
    /* S_KM_HINTCLICK*/ L"Click the image to set the point",
    /* S_KM_X       */ L"X",
    /* S_KM_Y       */ L"Y",
    /* S_KM_X2      */ L"X2",
    /* S_KM_Y2      */ L"Y2",
    /* S_KM_SHOT    */ L"Take screenshot",
    /* S_PERF2_TITLE*/ L"Performance Center",
    /* S_PERF2_SUB  */ L"Live stats: CPU, RAM, disk for the last 60 seconds",
    /* S_PERF2_CPU  */ L"CPU load (QEMU)",
    /* S_PERF2_RAM  */ L"Process RAM",
    /* S_PERF2_DISK */ L"Disk used",
    /* S_PERF2_NOINST*/ L"No running instances. Start Android to see statistics.",
    /* S_PERF2_REC  */ L"Recommendations",
    /* S_PERF2_ECO  */ L"Eco mode (no graphs)",
    /* S_PERF2_UPTIME*/ L"Uptime",
    /* S_PERF2_GPU  */ L"GPU mode",
    /* S_WIZ_TITLE  */ L"Instance Creation Wizard",
    /* S_WIZ_STEP   */ L"Step",
    /* S_WIZ_NEXT   */ L"Next →",
    /* S_WIZ_PREV   */ L"← Back",
    /* S_WIZ_FINISH */ L"Done",
    /* S_WIZ_NAME   */ L"Instance name",
    /* S_WIZ_TEMPLATE*/ L"Template",
    /* S_WIZ_T_CLEAN*/ L"Clean Android",
    /* S_WIZ_T_BAL  */ L"Balanced",
    /* S_WIZ_T_PERF */ L"Performance",
    /* S_WIZ_T_ECO  */ L"Economical",
    /* S_WIZ_T_TEST */ L"APK testing",
    /* S_WIZ_T_PORT */ L"Portrait phone",
    /* S_WIZ_T_TAB  */ L"Landscape tablet",
    /* S_WIZ_T_CUSTOM*/ L"Custom",
    /* S_WIZ_PERF   */ L"Performance",
    /* S_WIZ_SCREEN */ L"Device screen",
    /* S_WIZ_INTEG  */ L"Integration",
    /* S_WIZ_REVIEW */ L"Review",
    /* S_WIZ_ADBLOCK*/ L"ADB on localhost only (127.0.0.1) - mandatory protection",
    /* S_WIZ_SHARED */ L"Shared folder with Windows",
    /* S_WIZ_SHORTCUT*/ L"Desktop shortcut",
    /* S_WIZ_OPEN   */ L"Open Android after creation",
    /* S_WIZ_SNAP   */ L"Create initial Clean Install snapshot",
    /* S_WIZ_PATH   */ L"Storage path",
    /* S_WIZ_SPACE  */ L"Required free space",
    /* S_WIZ_CREATE */ L"Create instance",
    /* S_WIZ_ORIENT */ L"Orientation",
    /* S_WIZ_LAND   */ L"Landscape",
    /* S_WIZ_PORT   */ L"Portrait",
    /* S_CLONE_TITLE*/ L"Clone instance",
    /* S_CLONE_FULL */ L"Full clone",
    /* S_CLONE_LINKED*/ L"Linked clone",
    /* S_CLONE_FULLD*/ L"Independent disk copy. Reliable, uses space. Recommended.",
    /* S_CLONE_LINKEDD*/ L"Fast and compact, but requires the parent disk to stay intact.",
    /* S_CLONE_KEYMAPS*/ L"Copy keymaps",
    /* S_CLONE_SHAREDC*/ L"Copy shared folder contents",
    /* S_APKMI_TITLE*/ L"Install APK to instances",
    /* S_APKMI_SUB  */ L"Select target instances (ADB must be connected)",
    /* S_APKMI_INSTALL*/ L"Install",
    /* S_APKMI_SNAPFIRST*/ L"Create snapshot before install",
    /* S_APKMI_RESULT*/ L"Result",
    /* S_APKMI_TIME */ L"Time",
    /* S_APKMI_ERR  */ L"Error",
    /* S_APKMI_DONE */ L"Installation finished",
    /* S_APK_ADDLIB */ L"Add to library",
    /* S_APK_WARN   */ L"This APK comes from an external source. Only install files you trust.",
    /* S_APK_DELETE2*/ L"Remove from library (keep file)",
    /* S_UPD_CHECK  */ L"Check for updates",
    /* S_UPD_CHANNEL*/ L"Update channel",
    /* S_UPD_STABLE */ L"Stable",
    /* S_UPD_BETA   */ L"Beta",
    /* S_UPD_DEV    */ L"Development",
    /* S_SET_MAXRUN */ L"Concurrent instance limit",
    /* S_MB_PARENTLINK*/ L"This instance has linked clones. Deleting the parent disk will break them. Continue?",
    /* S_MB_IMPORTOK*/ L"Import completed successfully",
    /* S_DIAG_EXPORT*/ L"Export report",
    /* S_AB_VER2    */ L"0.4.0 Universal",
    // ---- stage 3 (TZ 3.0)
    /* S3_GPU_FB_HOST    */ L"Host GPU mode unavailable. SwiftShader used. Update your GPU driver for hardware acceleration.",
    /* S3_GPU_FB_DRIVER  */ L"Problematic GPU driver detected. SwiftShader used. Please update the GPU driver.",
    /* S3_GPU_FB_NOVIRGL */ L"QEMU build has no virtio-gpu-gl. SwiftShader software rendering used.",
    /* S3_GPU_FB_NOWHPX  */ L"WHPX unavailable. Enable 'Windows Hypervisor Platform' and BIOS virtualization. Software rendering used.",
    /* S3_PROFILE_RUNNING*/ L"Stop the instance before changing the performance profile.",
    /* S3_PKG_ERROR      */ L"Package download error",
    /* S3_PKG_DOWNLOAD   */ L"Downloading full package…",
    /* S3_PKG_EXTRACT    */ L"Extracting package…",
    /* S3_PKG_VERIFY     */ L"Verifying SHA-256…",
    /* S3_PKG_DONE       */ L"Package installed and verified",
    /* S3_PKG_BADSHA     */ L"SHA-256 checksum mismatch:",
    /* S3_PKG_BADSIZE    */ L"File size does not match expected",
    /* S3_PKG_NET        */ L"Failed to download package",
    /* S3_PKG_SMALL      */ L"File is too small for a NovaDroid package",
    /* S3_REC_TITLE      */ L"Crash recovery",
    /* S3_REC_QUESTION   */ L"Choose an action:",
    /* S3_REC_SNAP       */ L"Restore latest snapshot",
    /* S3_REC_LOGS       */ L"Open logs",
    /* S3_REC_REPORT     */ L"Save error report (ZIP)",
    /* S3_REC_SAVED      */ L"Report saved",
    /* S3_WIZ_TITLE      */ L"NovaDroid full package",
    /* S3_WIZ_SUB        */ L"On first start the app downloads the full package (QEMU + ADB + Android x86_64 image). Emulator start becomes available after download and verification.",
    /* S3_WIZ_TOTAL      */ L"Total",
    /* S3_WIZ_READY      */ L"Done! Package downloaded, verified (SHA-256) and extracted. The emulator is ready.",
    /* S3_WIZ_DOWNLOAD   */ L"Download package",
    /* S3_WIZ_OFFZIP     */ L"Offline ZIP",
    /* S3_WIZ_VERIFY     */ L"Verify files",
    /* S3_WIZ_PICKZIP    */ L"Select the downloaded package ZIP",
    /* S3_WIZ_HIDE       */ L"Hide",
    /* S3_PKG_TITLE      */ L"Full package (QEMU + ADB + Android image)",
    /* S3_PKG_OK         */ L"Installed",
    /* S3_PKG_PARTIAL    */ L"WARNING: package files are missing!",
    /* S3_PKG_NO         */ L"Not installed. Emulator start is blocked until the package is downloaded.",
    /* S3_PKG_REDOWNLOAD */ L"Re-download",
    /* S3_PKG_STARTED    */ L"Package download started",
    /* S3_PKG_BUSY       */ L"Download already in progress",
    /* S3_PKG_VOK        */ L"Verification passed",
    /* S3_PKG_VFAIL      */ L"Verification failed",
    /* S3_PROF_TITLE     */ L"Gaming performance profiles",
    /* S3_PROF_HINT      */ L"The profile is applied to the selected instance. Stop the instance before applying.",
    /* S3_PROF_APPLIED   */ L"Profile applied:",
    /* S3_GPU_TITLE      */ L"GPU status",
    /* S3_G_TITLE        */ L"Graphics & gaming",
    /* S3_G_GPUMODE      */ L"GPU mode",
    /* S3_G_BACKEND      */ L"GPU Backend",
    /* S3_G_SCALE        */ L"Scaling",
    /* S3_G_PROFILE      */ L"Performance profile",
    /* S3_G_BORDERLESS   */ L"Borderless window",
    /* S3_G_TOPMOST      */ L"Always on top",
    /* S3_G_VSYNC        */ L"VSync",
    /* S3_G_OVERLAY      */ L"FPS counter in window",
    /* S3_G_QUICKSTART   */ L"Fast start",
    /* S3_G_VOLUME       */ L"Volume, %",
    /* S3_G_MUTEMIN      */ L"Mute when minimized",
    /* S3_G_INVY         */ L"Invert Y axis",
    /* S3_G_HOTKEY       */ L"Mouse capture key",
    /* S3_G_PROBE        */ L"Test GPU",
    /* S3_G_RESOLVED     */ L"Mode",
    /* S3_GPU_AUTO       */ L"Auto",
    /* S3_GPU_HOST       */ L"Host (host GPU)",
    /* S3_GPU_SWIFT      */ L"SwiftShader (fast software)",
    /* S3_GPU_SOFT       */ L"Software",
    /* S3_BK_AUTO        */ L"Auto",
    /* S3_FPS_OFF        */ L"Unlimited",
    /* S3_SC_FIT         */ L"Aspect Fit",
    /* S3_SC_STRETCH     */ L"Stretch",
    /* S3_SC_FILL        */ L"Aspect Fill",
    /* S3_SC_NATIVE      */ L"Native (1:1)",
    /* S3_TB_FULL        */ L"Fullscreen (F11)",
    /* S3_TB_CAP         */ L"Mouse (RCtrl)",
    /* S3_TB_MUTE        */ L"Sound on/off",
    // ---- stage 4-7 (TZ 4-7)
    /* S4_ABI_OK         */ L"APK contains x86_64 libraries. Compatible.",
    /* S4_ABI_X86        */ L"APK contains x86 libraries. Compatible (32-bit).",
    /* S4_ABI_ARM        */ L"APK contains ARM libraries only. Problems are possible.",
    /* S4_ABI_UNIVERSAL  */ L"APK has no native libraries - universal. Compatible.",
    /* S4_ABI_UNKNOWN    */ L"Could not determine APK ABI.",
    /* S4_ABI_NOLIBS     */ L"no native libraries",
    /* S4_NET_RESULT     */ L"Network",
    /* S4_NET_FIXFAIL    */ L"Failed to apply DNS. Try restarting the instance.",
    /* S4_NET_INETOK     */ L"Internet OK",
    /* S4_NET_INETFAIL   */ L"Internet FAIL",
    /* S4_NET_DIAG       */ L"Network diagnostics",
    /* S4_NET_FIXDNS     */ L"DNS 8.8.8.8 / 1.1.1.1",
    /* S4_NET_RESETDNS   */ L"Reset DNS",
    /* S4_NET_RUNNING    */ L"Running diagnostics...",
    /* S4_NET_FIXED      */ L"DNS applied (8.8.8.8, 1.1.1.1). Saved to instance config.",
    /* S4_NET_RESETOK    */ L"DNS reset to 10.0.2.3 (on next start).",
    /* S4_SENS_FAIL      */ L"Failed. Make sure the instance is running and ADB is connected.",
    /* S4_SENS_OK        */ L"Applied.",
    /* S4_GPS_BADFMT     */ L"Format: latitude,longitude (e.g. 55.7558,37.6173).",
    /* S4_PROF_OK        */ L"Profile applied.",
    /* S4_APP_PUBG       */ L"Anti-cheat issues possible on some servers",
    /* S4_APP_APPLIED    */ L"App profile applied: %s",
    /* S4_COM_TITLE      */ L"Compatibility",
    /* S4_COM_SUB        */ L"APK analysis (ABI), device and app profiles",
    /* S4_COM_APK        */ L"APK analysis",
    /* S4_COM_APKHINT    */ L"Check APK architecture (ABI), version and SDK requirements before installing.",
    /* S4_COM_ANALYZE    */ L"Pick APK...",
    /* S4_COM_RESCAN     */ L"Rescan library",
    /* S4_COM_RESCANNED  */ L"APK library enriched with ABI data.",
    /* S4_COM_PKG        */ L"Package",
    /* S4_NOSEL          */ L"Select an instance first",
    /* S4_COM_DEV        */ L"Device profiles",
    /* S4_COM_DEVSUB     */ L"Apply to selected instance: %s",
    /* S4_COM_APP        */ L"App profiles",
    /* S4_COM_APPSUB     */ L"Recommended settings are applied automatically on APK install.",
    /* S4_COM_APPLY      */ L"Apply",
    /* S4_COM_WARN       */ L"No guarantee that all games and apps work. Anti-cheat systems (device identity spoofing) are not and will not be bypassed.",
    /* S4_SENS_TITLE     */ L"Sensors & Network",
    /* S4_SENS_SUB       */ L"GPS, orientation, battery, network diagnostics of the selected instance",
    /* S4_NET_TITLE      */ L"Network (10.0.2.x)",
    /* S4_NET_HINT       */ L"Standard model: gateway 10.0.2.1, host 10.0.2.2, DNS 10.0.2.3. Manual DNS is saved to config.",
    /* S4_GPS_TITLE      */ L"GPS",
    /* S4_GPS_HINT       */ L"Set coordinates (works in apps supporting mock locations).",
    /* S4_GPS_SET        */ L"Set",
    /* S4_GPS_CUSTOM     */ L"Custom coordinates: latitude,longitude",
    /* S4_ORI_TITLE      */ L"Orientation / accelerometer",
    /* S4_ORI_HINT       */ L"Rotate instance screen (auto-rotation lock).",
    /* S4_BAT_TITLE      */ L"Battery",
    /* S4_BAT_HINT       */ L"Charge level and state (charging/discharging).",
    /* S4_BAT_SET        */ L"Set",
    /* S4_BAT_RESET      */ L"Reset",
    /* S4_BAT_CUSTOM     */ L"Custom level: 0-100 (state: charging)",
    /* S4_ADV_TITLE      */ L"Advanced",
    /* S4_ADV_SUB        */ L"Updates, stream, plugins, cloud, macros, sync, Discord",
    /* S4_UPD_TITLE      */ L"Updates",
    /* S4_UPD_CUR        */ L"Current version",
    /* S4_UPD_CHANNEL    */ L"Channel",
    /* S4_UPD_AVAIL      */ L"Version %s is available - install it.",
    /* S4_UPD_LATEST     */ L"You have the latest version.",
    /* S4_UPD_INSTALL    */ L"Install",
    /* S4_UPD_CHANGETO   */ L"Channel",
    /* S4_UPD_NOFEED     */ L"Update source not configured (updates.json).",
    /* S4_UPD_DLFAIL     */ L"Download failed",
    /* S4_UPD_BADSHA     */ L"SHA-256 check failed. Update cancelled.",
    /* S4_UPD_SWAPFAIL   */ L"Cannot replace exe (running?).",
    /* S4_UPD_ROLLBACK   */ L"Install failed, rolled back.",
    /* S4_LOG_TITLE      */ L"Logs & export",
    /* S4_LOG_HINT       */ L"Collect QEMU + launcher + Android logcat into a ZIP.",
    /* S4_LOG_EXPORT     */ L"Export logs (ZIP)",
    /* S4_LOG_ZIPPING    */ L"Collecting logs...",
    /* S4_LOG_DONE       */ L"Done: %s",
    /* S4_LOG_FAIL       */ L"Failed to collect logs.",
    /* S4_BASEPART       */ L"Some apps failed to install (see log).",
    /* S4_BASEDONE       */ L"Base apps installed (F-Droid, APKPure).",
    /* S4_STR_TITLE      */ L"View in browser",
    /* S4_STR_HINT       */ L"Stream Android screen + mouse/keyboard control. Localhost only, tokenized link.",
    /* S4_STR_START      */ L"Start streaming",
    /* S4_STR_STOP       */ L"Stop streaming",
    /* S4_STR_OPEN       */ L"Open in browser",
    /* S4_STR_LOCAL      */ L"localhost only",
    /* S4_STR_BUSY       */ L"Streaming is already running.",
    /* S4_STR_PORTBUSY   */ L"Port %d is busy.",
    /* S4_PLG_TITLE      */ L"Plugins",
    /* S4_PLG_HINT       */ L"DLL + manifest.json inside the plugins folder. SHA-256 verified before load.",
    /* S4_PLG_EMPTY      */ L"No plugins. Put them into %s next to the program.",
    /* S4_PLG_INVALID    */ L"Corrupted or hash check failed",
    /* S4_PLG_ON         */ L"Enable",
    /* S4_PLG_OFF        */ L"Disable",
    /* S4_PLG_RESCAN     */ L"Rescan",
    /* S4_PLG_RESCANNED  */ L"Plugins rescanned.",
    /* S4_CLD_TITLE      */ L"Cloud backups",
    /* S4_CLD_PROV       */ L"Provider",
    /* S4_CLD_NOTSET     */ L"not configured",
    /* S4_CLD_ENC        */ L"AES-256 encryption",
    /* S4_CLD_NOENC      */ L"no encryption",
    /* S4_CLD_SETUP      */ L"Configure",
    /* S4_CLD_NOPROV     */ L"Provider not supported.",
    /* S4_CLD_NOTSET2    */ L"Configure the cloud first.",
    /* S4_CLD_NOFILES    */ L"No backups found in the cloud.",
    /* S4_CLD_PICKFILE   */ L"File name to restore:",
    /* S4_CLD_NOTHING    */ L"Nothing to back up.",
    /* S4_CLD_UPOK       */ L"Backup uploaded to the cloud.",
    /* S4_CLD_UPFAIL     */ L"Backup failed",
    /* S4_CLD_RESOK      */ L"Restore finished. Restart the program.",
    /* S4_CLD_RESFAIL    */ L"Restore failed",
    /* S4_CLD_SETUPT     */ L"Cloud",
    /* S4_CLD_SERVER     */ L"Server",
    /* S4_CLD_TOKEN      */ L"Token (OAuth / user:pass)",
    /* S4_CLD_ENC_ON     */ L"AES-256 encryption: ON",
    /* S4_CLD_ENC_OFF    */ L"AES-256 encryption: OFF",
    /* S4_CLD_NOTE       */ L"Token is stored locally and never included in backups. Backed up: settings, keymaps, APK list, macros.",
    /* S4_MAC_TITLE      */ L"Macros & automation",
    /* S4_MAC_WARN       */ L"Warning: using macros in online games may lead to account bans.",
    /* S4_MAC_EMPTY      */ L"Record your first macro with the button below (Esc to stop).",
    /* S4_MAC_STEPS      */ L"steps",
    /* S4_MAC_EDIT       */ L"Edit",
    /* S4_MAC_PLAY       */ L"Play",
    /* S4_MAC_STOP       */ L"Stop",
    /* S4_MAC_DEL        */ L"Delete",
    /* S4_MAC_REC        */ L"Record macro",
    /* S4_MAC_STOPREC    */ L"Stop recording",
    /* S4_MAC_RECON      */ L"Recording (Esc to stop). Click inside the emulator window.",
    /* S4_MAC_SAVED      */ L"Macro recorded: %d steps.",
    /* S4_MAC_DEFNAME    */ L"Macro %s",
    /* S4_MAC_NORUN      */ L"Instance is not running.",
    /* S4_MAC_PLAYING    */ L"A macro is already playing.",
    /* S4_MAC_PLAYDONE   */ L"Playback finished.",
    /* S4_MAC_DELETED    */ L"Macro deleted.",
    /* S4_MAC_EDITORT    */ L"Macro editor",
    /* S4_MAC_NOHOT      */ L"Hotkey",
    /* S4_MAC_REPEAT     */ L"Repeats",
    /* S4_MAC_ADDTAP     */ L"+ Tap",
    /* S4_MAC_ADDKEY    */ L"+ Key",
    /* S4_MAC_ADDWAIT    */ L"+ Wait",
    /* S4_MAC_ADDTEXT    */ L"+ Text",
    /* S4_MAC_DELSTEP    */ L"- Step",
    /* S4_SYN_TITLE      */ L"Window sync",
    /* S4_SYN_HINT       */ L"Master instance drives the slaves: taps, keys and macros are mirrored.",
    /* S4_SYN_NONE       */ L"No groups. Select a running instance and create a group.",
    /* S4_SYN_ADD        */ L"Create group (master = selected)",
    /* S4_SYN_REMOVE     */ L"Remove group of selected",
    /* S4_SYN_ISMASTER   */ L"This instance is already a master of another group.",
    /* S4_SYN_NOSLAVES   */ L"No other running instances to use as slaves.",
    /* S4_SYN_ADDED      */ L"Group created: %d slaves.",
    /* S4_SYN_REMOVED    */ L"Group removed.",
    /* S4_ALG_TITLE      */ L"Anti-lag & FPS",
    /* S4_ALG_HINT       */ L"On FPS drops: process priority is raised, quality recommendations shown.",
    /* S4_ALG_ON         */ L"Anti-lag: ON",
    /* S4_ALG_OFF        */ L"Anti-lag: OFF",
    /* S4_DSC_TITLE      */ L"Discord Rich Presence",
    /* S4_DSC_HINT       */ L"'Playing <instance> via NovaDroid'. Requires running Discord. Own Client ID - in settings.",
    /* S4_DSC_ON         */ L"Enable",
    /* S4_DSC_OFF        */ L"Disable",
    /* S4_PRO_HINT       */ L"Pro: priority support, early access, extended macros, exclusive themes.",
    /* S4_PRO_ACT        */ L"Activate key",
    /* S4_PRO_ACTIVE     */ L"Pro activated",
    /* S4_PRO_ISACTIVE   */ L"Key: %s",
    /* S4_PRO_ENTER      */ L"NovaDroid Pro key",
    /* S4_PRO_OK         */ L"NovaDroid Pro activated. Thank you!",
    /* S4_PRO_BAD        */ L"Invalid key format (NOVA-XXXX-...).",
    /* S4_NAV_COMPAT     */ L"Compatibility",
    /* S4_NAV_SENSORS    */ L"Sensors & Network",
    /* S4_NAV_ADVANCED   */ L"Advanced",
    /* S4_WIZ_WELCOME    */ L"Welcome to NovaDroid",
    /* S4_WIZ_CHECK      */ L"System check",
    /* S4_WIZ_LANG       */ L"Interface language",
    /* S4_WIZ_THEME      */ L"Theme",
    /* S4_WIZ_INST       */ L"First instance",
    /* S4_WIZ_DONE       */ L"All set",
    /* S4_WIZ_STEP       */ L"Step",
    /* S4_WIZ_WELCOMETXT */ L"The wizard will set up NovaDroid in five steps: system check, language, theme and creating your first Android instance.",
    /* S4_WIZ_NOVIRT     */ L"Enable VT-x/AMD-V in BIOS",
    /* S4_WIZ_NOWHPX     */ L"Enable the Windows Hypervisor Platform feature",
    /* S4_WIZ_DISK       */ L"Disk",
    /* S4_WIZ_SYSWARN    */ L"Not all requirements are met - performance issues are possible.",
    /* S4_WIZ_DARK       */ L"Dark",
    /* S4_WIZ_LIGHT      */ L"Light",
    /* S4_WIZ_SYS        */ L"Follow system",
    /* S4_WIZ_LAUNCH     */ L"Launch NovaDroid",
    /* S4_WIZ_DOCS       */ L"Open documentation",
    /* S4_WIZ_DONETXT    */ L"Done! The first instance has been created. Documentation is available in the About section and in the docs folder.",
};

int g_lang = 0;

static_assert(sizeof(RU) / sizeof(RU[0]) == S_COUNT_, "RU string table mismatch");
static_assert(sizeof(EN) / sizeof(EN[0]) == S_COUNT_, "EN string table mismatch");

const wchar_t* T(int id) {
    if (id < 0 || id >= S_COUNT_) return L"?";
    return g_lang == 0 ? RU[id] : EN[id];
}
